[package]
name = "soliscloud-mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21"
chrono = "0.4"
convert_case = "0.6"
hmac = "0.12"
log = "0.4"
md5 = "0.7"
mqtt-reeze = "0.1"
pretty_env_logger = "0.5"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
